### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by IceDBorn** [kaii-lb/overskride#10]
https://github.com/NixOS/nixpkgs/issues/259489

**Comment by SayantanRC** [comment]
Yes. It'd be great.

**Comment by IceDBorn** [comment]
https://github.com/NixOS/nixpkgs/issues/259489

**Comment by IceDBorn** [comment]
I'm aware, I just made this issue to attach the nixpkgs issue.

**Comment by fufexan** [comment]
To any nixer wanting to try it out, I've hackily updated gtk4/libadwaita and created a derivation for overskride [here](https://github.com/fufexan/nixpkgs/tree/overskride).

**Comment by drawbu** [comment]
I think we can close this as Overskride is now on the Nixpkgs repository.
See [nixpkgs/269055](https://github.com/NixOS/nixpkgs/pull/269055#event-11351611099).

**Comment by SayantanRC** [comment]
Can confirm its presence on the unstable channel for now.

**Comment by kaii-lb** [comment]
alright, since its on unstable imma close this.
