### ISSUE TITLE
Rename titles for side bar and main area

### ISSUE THREAD

**Issue by acerspyro** [kaii-lb/overskride#16]
It doesn't seem usual for Adwaita apps to have the sidebar labeled as "Sidebar".

Typically, applications will put their app name or the contents of the side bar as the title of the side bar, and will put the current state / location as the title of the main area.

![image](https://github.com/kaii-lb/overskride/assets/4400999/952c41f1-4a86-4e42-8141-51d9526b7cee)
![image](https://github.com/kaii-lb/overskride/assets/4400999/e3034859-f612-43e4-9169-ec2ab973ede8)
![image](https://github.com/kaii-lb/overskride/assets/4400999/317596a5-c1c9-4229-8659-3af7f9337cdd)
![image](https://github.com/kaii-lb/overskride/assets/4400999/bcad4241-3162-4144-8295-d2ea5d32cd00)

I recommend the side bar say "Overskride" or "Bluetooth", and the main portion either say "Device" or has the name of the device.

If the main portion has the name of the device, the text under the icon should either be removed or state the type of the device.

**Comment by kaii-lb** [comment]
thank you for the (quite detailed) report, i did change it to "Overskride" on the sidebar and "Settings" or "Device" for the main window title
