### ISSUE TITLE
issue with hyprland

### ISSUE THREAD

**Issue by user12xxxxxx** [kaii-lb/overskride#22]
![240302_20h36m59s_screenshot](https://github.com/kaii-lb/overskride/assets/111512589/9db774f5-a645-44fb-af85-43538e161fc3)
so i applied the transparency but for some reason it only works for daughter window.
i also set it to float which also doesn't work

**Comment by kaii-lb** [comment]
this isn't an overskride thing it's a GTK thing. consult with the respective devs

**Comment by user12xxxxxx** [comment]
okay 
thanks for quick reponse
