### ISSUE TITLE
Build artifact expired

### ISSUE THREAD

**Issue by alyssadev** [kaii-lb/overskride#23]
No downloads are available as indicated in README, as actions build artifacts have expired.

**Comment by kaii-lb** [comment]
ohhh i did not notice that. i'll fix this in a sec. thank you for pointing it out.

**Comment by kaii-lb** [comment]
check the latest release and please report if it works or not

**Comment by alyssadev** [comment]
https://github.com/kaii-lb/overskride/actions/runs/8408171165 The build failed

**Comment by kaii-lb** [comment]
not the build, but the releases page

**Comment by alyssadev** [comment]
This build is amd64, the device I wanted to run it on is arm64. I'll see if I can fix the build process and get it working and PR a fix for main.yml that provides multi arch support. The lack of binary download has been resolved so I'll close this issue
