### ISSUE TITLE
[Enhancement] Many, many unknown devices

### ISSUE THREAD

**Issue by BobVarioa** [kaii-lb/overskride#24]
The list of devices seems to flash with a large amount of unknown devices, perhaps there could be a way to block them?
![2024-03-28T08:56:57,635451254-05:00](https://github.com/kaii-lb/overskride/assets/60078104/b8d4eb8a-d49d-4895-9146-08e92182410b)

**Comment by kaii-lb** [comment]
added :D

**Comment by BobVarioa** [comment]
this seems to work! however, it doesn't seem to persist between closing and reopening the app
