### ISSUE TITLE
Profiles unavailable for Sony WH-1000XM4

### ISSUE THREAD

**Issue by fcoelhomrc** [kaii-lb/overskride#28]
The device is automatically restricted to HSP profiles, although it has support for A2DP.

I think the reason is that the device is locked as a output and input sink, which restricts the profiles to HSP.

How can I disable the headset mic, to ensure it runs solely as output A2DP audio sink?

**Comment by kaii-lb** [comment]
i only just ggot the notification that this issue even existed, have you managed to fix it?

**Comment by fcoelhomrc** [comment]
one of those things that magically fixed itself
