### ISSUE TITLE
Unit dbus-org.bluez.service not found

### ISSUE THREAD

**Issue by gmankab** [kaii-lb/overskride#3]
```text
[I] ➜  ~ flatpak run io.github.kaii_lb.Overskride

(overskride:2): Gtk-WARNING **: 01:52:01.673: Unknown key gtk-modules in /home/gmanka/.var/app/io.github.kaii_lb.Overskride/config/gtk-4.0/settings.ini

(overskride:2): Gtk-WARNING **: 01:52:01.826: 'center' is not a valid child type of 'AdwHeaderBar'
thread 'main' panicked at src/window.rs:187:40:
cannot start presetup, something got REALLY fucked: Error { kind: Internal(DBus("org.freedesktop.systemd1.NoSuchUnit")), message: "Unit dbus-org.bluez.service not found." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

my system is arch + gnome, i have bluez installed

upd:

fixed by `sudo systemctl enable --now bluetooth`

also a am getting same error if i plug out the bluetooth dongle

can you please make user friendly massage about a problem if user forgot  to run `sudo systemctl enable --now bluetooth` or if user forgot to plug in the bluetooth dongle

**Comment by kaii-lb** [comment]
> also a am getting same error if i plug out the bluetooth dongle

yes ofcourse you would, the entire app depends on bluetooth existing and being enabled by systemd kr wtv service manager you use.
later on i plan to add a message for this special case, but for now you a bluetooth app wont work without bluetooth-

ill keep this open as a reminder

**Comment by gmankab** [comment]
thank you!

**Comment by kaii-lb** [comment]
this is done, closing
