### ISSUE TITLE
no icon

### ISSUE THREAD

**Issue by gmankab** [kaii-lb/overskride#4]
![image](https://github.com/kaii-lb/overskride/assets/73340745/e8a5e0fa-8d87-4bcb-92a1-deb9b7d273a0)

can you please add an icon

**Comment by davidphilipbarr** [comment]
i've submitted a PR for this 
![Screenshot from 2023-10-18 19-13-41](https://github.com/kaii-lb/overskride/assets/93874/f7e9a97d-1242-4240-b0c4-db914d987f43)

**Comment by kaii-lb** [comment]
oh that icon is really good, thank you!
i'll close this and merge the PR
