### ISSUE TITLE
SBC-XQ support

### ISSUE THREAD

**Issue by Anderhar** [kaii-lb/overskride#9]
Please make sure that Overskride assists user to utilize [SBC XQ](https://en.wikipedia.org/wiki/SBC_(codec)#Higher_quality_variants) profile when paring with audio playback devices. SBC XQ is an enhancement to the Bluetooth SBC audio codec that can achieve aptX HD sound quality even on cheaper audio devices. It is already supported by PipeWire.

**Comment by kaii-lb** [comment]
done, took a lot less work than expected
